//
// x64\Debug\distribution2d_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_X64_DEBUG_DISTRIBUTION2D_ISPC_H
#define ISPC_X64_DEBUG_DISTRIBUTION2D_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_X64_DEBUG_DISTRIBUTION2D_ISPC_H
