//
// x64\Debug\pathtracer_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_X64_DEBUG_PATHTRACER_ISPC_H
#define ISPC_X64_DEBUG_PATHTRACER_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void *  PathTracer__new(const int32_t &maxDepth, const float &minContribution, const float &epsilon, const int32_t &spp, void * backplate, const int32_t &sampleLightForGlossy);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_X64_DEBUG_PATHTRACER_ISPC_H
