//
// x64\ReleaseAVX2\framebuffer_rgb8_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_X64_RELEASEAVX2_FRAMEBUFFER_RGB8_ISPC_H
#define ISPC_X64_RELEASEAVX2_FRAMEBUFFER_RGB8_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_X64_RELEASEAVX2_FRAMEBUFFER_RGB8_ISPC_H
